// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: Google.capnp

package eu.hippix.bsctest.data.capnp;

public final class GoogleCapnp {
  public static class Google {
    public static final org.capnproto.StructSize STRUCT_SIZE = new org.capnproto.StructSize((short)0,(short)4);
    public static final class Factory extends org.capnproto.StructFactory<Builder, Reader> {
      public Factory() {
      }
      public final Reader constructReader(org.capnproto.SegmentReader segment, int data,int pointers, int dataSize, short pointerCount, int nestingLimit) {
        return new Reader(segment,data,pointers,dataSize,pointerCount,nestingLimit);
      }
      public final Builder constructBuilder(org.capnproto.SegmentBuilder segment, int data,int pointers, int dataSize, short pointerCount) {
        return new Builder(segment, data, pointers, dataSize, pointerCount);
      }
      public final org.capnproto.StructSize structSize() {
        return Google.STRUCT_SIZE;
      }
      public final Reader asReader(Builder builder) {
        return builder.asReader();
      }
    }
    public static final Factory factory = new Factory();
    public static final org.capnproto.StructList.Factory<Builder,Reader> listFactory =
      new org.capnproto.StructList.Factory<Builder, Reader>(factory);
    public static final class Builder extends org.capnproto.StructBuilder {
      Builder(org.capnproto.SegmentBuilder segment, int data, int pointers,int dataSize, short pointerCount){
        super(segment, data, pointers, dataSize, pointerCount);
      }
      public final Reader asReader() {
        return new Reader(segment, data, pointers, dataSize, pointerCount, 0x7fffffff);
      }
      public final boolean hasStatus() {
        return !_pointerFieldIsNull(0);
      }
      public final org.capnproto.Text.Builder getStatus() {
        return _getPointerField(org.capnproto.Text.factory, 0, null, 0, 0);
      }
      public final void setStatus(org.capnproto.Text.Reader value) {
        _setPointerField(org.capnproto.Text.factory, 0, value);
      }
      public final void setStatus(String value) {
        _setPointerField(org.capnproto.Text.factory, 0, new org.capnproto.Text.Reader(value));
      }
      public final org.capnproto.Text.Builder initStatus(int size) {
        return _initPointerField(org.capnproto.Text.factory, 0, size);
      }
      public final boolean hasAvailableTravelModes() {
        return !_pointerFieldIsNull(1);
      }
      public final org.capnproto.TextList.Builder getAvailableTravelModes() {
        return _getPointerField(org.capnproto.TextList.factory, 1, null, 0);
      }
      public final void setAvailableTravelModes(org.capnproto.TextList.Reader value) {
        _setPointerField(org.capnproto.TextList.factory, 1, value);
      }
      public final org.capnproto.TextList.Builder initAvailableTravelModes(int size) {
        return _initPointerField(org.capnproto.TextList.factory, 1, size);
      }
      public final boolean hasRoutes() {
        return !_pointerFieldIsNull(2);
      }
      public final org.capnproto.StructList.Builder<eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Routes.Builder> getRoutes() {
        return _getPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Routes.listFactory, 2, null, 0);
      }
      public final void setRoutes(org.capnproto.StructList.Reader<eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Routes.Reader> value) {
        _setPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Routes.listFactory, 2, value);
      }
      public final org.capnproto.StructList.Builder<eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Routes.Builder> initRoutes(int size) {
        return _initPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Routes.listFactory, 2, size);
      }
      public final boolean hasGeocodedWaypoints() {
        return !_pointerFieldIsNull(3);
      }
      public final org.capnproto.StructList.Builder<eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.GeocodedWaypoints.Builder> getGeocodedWaypoints() {
        return _getPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.GeocodedWaypoints.listFactory, 3, null, 0);
      }
      public final void setGeocodedWaypoints(org.capnproto.StructList.Reader<eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.GeocodedWaypoints.Reader> value) {
        _setPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.GeocodedWaypoints.listFactory, 3, value);
      }
      public final org.capnproto.StructList.Builder<eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.GeocodedWaypoints.Builder> initGeocodedWaypoints(int size) {
        return _initPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.GeocodedWaypoints.listFactory, 3, size);
      }
    }

    public static final class Reader extends org.capnproto.StructReader {
      Reader(org.capnproto.SegmentReader segment, int data, int pointers,int dataSize, short pointerCount, int nestingLimit){
        super(segment, data, pointers, dataSize, pointerCount, nestingLimit);
      }

      public boolean hasStatus() {
        return !_pointerFieldIsNull(0);
      }
      public org.capnproto.Text.Reader getStatus() {
        return _getPointerField(org.capnproto.Text.factory, 0, null, 0, 0);
      }

      public final boolean hasAvailableTravelModes() {
        return !_pointerFieldIsNull(1);
      }
      public final org.capnproto.TextList.Reader getAvailableTravelModes() {
        return _getPointerField(org.capnproto.TextList.factory, 1, null, 0);
      }

      public final boolean hasRoutes() {
        return !_pointerFieldIsNull(2);
      }
      public final org.capnproto.StructList.Reader<eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Routes.Reader> getRoutes() {
        return _getPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Routes.listFactory, 2, null, 0);
      }

      public final boolean hasGeocodedWaypoints() {
        return !_pointerFieldIsNull(3);
      }
      public final org.capnproto.StructList.Reader<eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.GeocodedWaypoints.Reader> getGeocodedWaypoints() {
        return _getPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.GeocodedWaypoints.listFactory, 3, null, 0);
      }

    }

    public static class OverviewPolyline {
      public static final org.capnproto.StructSize STRUCT_SIZE = new org.capnproto.StructSize((short)0,(short)1);
      public static final class Factory extends org.capnproto.StructFactory<Builder, Reader> {
        public Factory() {
        }
        public final Reader constructReader(org.capnproto.SegmentReader segment, int data,int pointers, int dataSize, short pointerCount, int nestingLimit) {
          return new Reader(segment,data,pointers,dataSize,pointerCount,nestingLimit);
        }
        public final Builder constructBuilder(org.capnproto.SegmentBuilder segment, int data,int pointers, int dataSize, short pointerCount) {
          return new Builder(segment, data, pointers, dataSize, pointerCount);
        }
        public final org.capnproto.StructSize structSize() {
          return Google.OverviewPolyline.STRUCT_SIZE;
        }
        public final Reader asReader(Builder builder) {
          return builder.asReader();
        }
      }
      public static final Factory factory = new Factory();
      public static final org.capnproto.StructList.Factory<Builder,Reader> listFactory =
        new org.capnproto.StructList.Factory<Builder, Reader>(factory);
      public static final class Builder extends org.capnproto.StructBuilder {
        Builder(org.capnproto.SegmentBuilder segment, int data, int pointers,int dataSize, short pointerCount){
          super(segment, data, pointers, dataSize, pointerCount);
        }
        public final Reader asReader() {
          return new Reader(segment, data, pointers, dataSize, pointerCount, 0x7fffffff);
        }
        public final boolean hasPoints() {
          return !_pointerFieldIsNull(0);
        }
        public final org.capnproto.Text.Builder getPoints() {
          return _getPointerField(org.capnproto.Text.factory, 0, null, 0, 0);
        }
        public final void setPoints(org.capnproto.Text.Reader value) {
          _setPointerField(org.capnproto.Text.factory, 0, value);
        }
        public final void setPoints(String value) {
          _setPointerField(org.capnproto.Text.factory, 0, new org.capnproto.Text.Reader(value));
        }
        public final org.capnproto.Text.Builder initPoints(int size) {
          return _initPointerField(org.capnproto.Text.factory, 0, size);
        }
      }

      public static final class Reader extends org.capnproto.StructReader {
        Reader(org.capnproto.SegmentReader segment, int data, int pointers,int dataSize, short pointerCount, int nestingLimit){
          super(segment, data, pointers, dataSize, pointerCount, nestingLimit);
        }

        public boolean hasPoints() {
          return !_pointerFieldIsNull(0);
        }
        public org.capnproto.Text.Reader getPoints() {
          return _getPointerField(org.capnproto.Text.factory, 0, null, 0, 0);
        }

      }

    }


    public static class Northeast {
      public static final org.capnproto.StructSize STRUCT_SIZE = new org.capnproto.StructSize((short)2,(short)0);
      public static final class Factory extends org.capnproto.StructFactory<Builder, Reader> {
        public Factory() {
        }
        public final Reader constructReader(org.capnproto.SegmentReader segment, int data,int pointers, int dataSize, short pointerCount, int nestingLimit) {
          return new Reader(segment,data,pointers,dataSize,pointerCount,nestingLimit);
        }
        public final Builder constructBuilder(org.capnproto.SegmentBuilder segment, int data,int pointers, int dataSize, short pointerCount) {
          return new Builder(segment, data, pointers, dataSize, pointerCount);
        }
        public final org.capnproto.StructSize structSize() {
          return Google.Northeast.STRUCT_SIZE;
        }
        public final Reader asReader(Builder builder) {
          return builder.asReader();
        }
      }
      public static final Factory factory = new Factory();
      public static final org.capnproto.StructList.Factory<Builder,Reader> listFactory =
        new org.capnproto.StructList.Factory<Builder, Reader>(factory);
      public static final class Builder extends org.capnproto.StructBuilder {
        Builder(org.capnproto.SegmentBuilder segment, int data, int pointers,int dataSize, short pointerCount){
          super(segment, data, pointers, dataSize, pointerCount);
        }
        public final Reader asReader() {
          return new Reader(segment, data, pointers, dataSize, pointerCount, 0x7fffffff);
        }
        public final double getLat() {
          return _getDoubleField(0);
        }
        public final void setLat(double value) {
          _setDoubleField(0, value);
        }

        public final double getLng() {
          return _getDoubleField(1);
        }
        public final void setLng(double value) {
          _setDoubleField(1, value);
        }

      }

      public static final class Reader extends org.capnproto.StructReader {
        Reader(org.capnproto.SegmentReader segment, int data, int pointers,int dataSize, short pointerCount, int nestingLimit){
          super(segment, data, pointers, dataSize, pointerCount, nestingLimit);
        }

        public final double getLat() {
          return _getDoubleField(0);
        }

        public final double getLng() {
          return _getDoubleField(1);
        }

      }

    }


    public static class Bounds {
      public static final org.capnproto.StructSize STRUCT_SIZE = new org.capnproto.StructSize((short)0,(short)2);
      public static final class Factory extends org.capnproto.StructFactory<Builder, Reader> {
        public Factory() {
        }
        public final Reader constructReader(org.capnproto.SegmentReader segment, int data,int pointers, int dataSize, short pointerCount, int nestingLimit) {
          return new Reader(segment,data,pointers,dataSize,pointerCount,nestingLimit);
        }
        public final Builder constructBuilder(org.capnproto.SegmentBuilder segment, int data,int pointers, int dataSize, short pointerCount) {
          return new Builder(segment, data, pointers, dataSize, pointerCount);
        }
        public final org.capnproto.StructSize structSize() {
          return Google.Bounds.STRUCT_SIZE;
        }
        public final Reader asReader(Builder builder) {
          return builder.asReader();
        }
      }
      public static final Factory factory = new Factory();
      public static final org.capnproto.StructList.Factory<Builder,Reader> listFactory =
        new org.capnproto.StructList.Factory<Builder, Reader>(factory);
      public static final class Builder extends org.capnproto.StructBuilder {
        Builder(org.capnproto.SegmentBuilder segment, int data, int pointers,int dataSize, short pointerCount){
          super(segment, data, pointers, dataSize, pointerCount);
        }
        public final Reader asReader() {
          return new Reader(segment, data, pointers, dataSize, pointerCount, 0x7fffffff);
        }
        public final eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Northeast.Builder getNortheast() {
          return _getPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Northeast.factory, 0, null, 0);
        }
        public final void setNortheast(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Northeast.Reader value) {
          _setPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Northeast.factory,0, value);
        }
        public final eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Northeast.Builder initNortheast() {
          return _initPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Northeast.factory,0, 0);
        }
        public final eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Northeast.Builder getSouthwest() {
          return _getPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Northeast.factory, 1, null, 0);
        }
        public final void setSouthwest(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Northeast.Reader value) {
          _setPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Northeast.factory,1, value);
        }
        public final eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Northeast.Builder initSouthwest() {
          return _initPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Northeast.factory,1, 0);
        }
      }

      public static final class Reader extends org.capnproto.StructReader {
        Reader(org.capnproto.SegmentReader segment, int data, int pointers,int dataSize, short pointerCount, int nestingLimit){
          super(segment, data, pointers, dataSize, pointerCount, nestingLimit);
        }

        public boolean hasNortheast() {
          return !_pointerFieldIsNull(0);
        }
        public eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Northeast.Reader getNortheast() {
          return _getPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Northeast.factory,0,null, 0);
        }

        public boolean hasSouthwest() {
          return !_pointerFieldIsNull(1);
        }
        public eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Northeast.Reader getSouthwest() {
          return _getPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Northeast.factory,1,null, 0);
        }

      }

    }


    public static class Distance {
      public static final org.capnproto.StructSize STRUCT_SIZE = new org.capnproto.StructSize((short)1,(short)1);
      public static final class Factory extends org.capnproto.StructFactory<Builder, Reader> {
        public Factory() {
        }
        public final Reader constructReader(org.capnproto.SegmentReader segment, int data,int pointers, int dataSize, short pointerCount, int nestingLimit) {
          return new Reader(segment,data,pointers,dataSize,pointerCount,nestingLimit);
        }
        public final Builder constructBuilder(org.capnproto.SegmentBuilder segment, int data,int pointers, int dataSize, short pointerCount) {
          return new Builder(segment, data, pointers, dataSize, pointerCount);
        }
        public final org.capnproto.StructSize structSize() {
          return Google.Distance.STRUCT_SIZE;
        }
        public final Reader asReader(Builder builder) {
          return builder.asReader();
        }
      }
      public static final Factory factory = new Factory();
      public static final org.capnproto.StructList.Factory<Builder,Reader> listFactory =
        new org.capnproto.StructList.Factory<Builder, Reader>(factory);
      public static final class Builder extends org.capnproto.StructBuilder {
        Builder(org.capnproto.SegmentBuilder segment, int data, int pointers,int dataSize, short pointerCount){
          super(segment, data, pointers, dataSize, pointerCount);
        }
        public final Reader asReader() {
          return new Reader(segment, data, pointers, dataSize, pointerCount, 0x7fffffff);
        }
        public final int getValue() {
          return _getIntField(0);
        }
        public final void setValue(int value) {
          _setIntField(0, value);
        }

        public final boolean hasText() {
          return !_pointerFieldIsNull(0);
        }
        public final org.capnproto.Text.Builder getText() {
          return _getPointerField(org.capnproto.Text.factory, 0, null, 0, 0);
        }
        public final void setText(org.capnproto.Text.Reader value) {
          _setPointerField(org.capnproto.Text.factory, 0, value);
        }
        public final void setText(String value) {
          _setPointerField(org.capnproto.Text.factory, 0, new org.capnproto.Text.Reader(value));
        }
        public final org.capnproto.Text.Builder initText(int size) {
          return _initPointerField(org.capnproto.Text.factory, 0, size);
        }
      }

      public static final class Reader extends org.capnproto.StructReader {
        Reader(org.capnproto.SegmentReader segment, int data, int pointers,int dataSize, short pointerCount, int nestingLimit){
          super(segment, data, pointers, dataSize, pointerCount, nestingLimit);
        }

        public final int getValue() {
          return _getIntField(0);
        }

        public boolean hasText() {
          return !_pointerFieldIsNull(0);
        }
        public org.capnproto.Text.Reader getText() {
          return _getPointerField(org.capnproto.Text.factory, 0, null, 0, 0);
        }

      }

    }


    public static class Steps {
      public static final org.capnproto.StructSize STRUCT_SIZE = new org.capnproto.StructSize((short)0,(short)7);
      public static final class Factory extends org.capnproto.StructFactory<Builder, Reader> {
        public Factory() {
        }
        public final Reader constructReader(org.capnproto.SegmentReader segment, int data,int pointers, int dataSize, short pointerCount, int nestingLimit) {
          return new Reader(segment,data,pointers,dataSize,pointerCount,nestingLimit);
        }
        public final Builder constructBuilder(org.capnproto.SegmentBuilder segment, int data,int pointers, int dataSize, short pointerCount) {
          return new Builder(segment, data, pointers, dataSize, pointerCount);
        }
        public final org.capnproto.StructSize structSize() {
          return Google.Steps.STRUCT_SIZE;
        }
        public final Reader asReader(Builder builder) {
          return builder.asReader();
        }
      }
      public static final Factory factory = new Factory();
      public static final org.capnproto.StructList.Factory<Builder,Reader> listFactory =
        new org.capnproto.StructList.Factory<Builder, Reader>(factory);
      public static final class Builder extends org.capnproto.StructBuilder {
        Builder(org.capnproto.SegmentBuilder segment, int data, int pointers,int dataSize, short pointerCount){
          super(segment, data, pointers, dataSize, pointerCount);
        }
        public final Reader asReader() {
          return new Reader(segment, data, pointers, dataSize, pointerCount, 0x7fffffff);
        }
        public final eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Distance.Builder getDuration() {
          return _getPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Distance.factory, 0, null, 0);
        }
        public final void setDuration(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Distance.Reader value) {
          _setPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Distance.factory,0, value);
        }
        public final eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Distance.Builder initDuration() {
          return _initPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Distance.factory,0, 0);
        }
        public final eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Northeast.Builder getEndLocation() {
          return _getPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Northeast.factory, 1, null, 0);
        }
        public final void setEndLocation(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Northeast.Reader value) {
          _setPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Northeast.factory,1, value);
        }
        public final eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Northeast.Builder initEndLocation() {
          return _initPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Northeast.factory,1, 0);
        }
        public final eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Distance.Builder getDistance() {
          return _getPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Distance.factory, 2, null, 0);
        }
        public final void setDistance(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Distance.Reader value) {
          _setPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Distance.factory,2, value);
        }
        public final eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Distance.Builder initDistance() {
          return _initPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Distance.factory,2, 0);
        }
        public final eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Northeast.Builder getStartLocation() {
          return _getPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Northeast.factory, 3, null, 0);
        }
        public final void setStartLocation(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Northeast.Reader value) {
          _setPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Northeast.factory,3, value);
        }
        public final eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Northeast.Builder initStartLocation() {
          return _initPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Northeast.factory,3, 0);
        }
        public final eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.OverviewPolyline.Builder getPolyline() {
          return _getPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.OverviewPolyline.factory, 4, null, 0);
        }
        public final void setPolyline(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.OverviewPolyline.Reader value) {
          _setPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.OverviewPolyline.factory,4, value);
        }
        public final eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.OverviewPolyline.Builder initPolyline() {
          return _initPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.OverviewPolyline.factory,4, 0);
        }
        public final boolean hasHtmlInstructions() {
          return !_pointerFieldIsNull(5);
        }
        public final org.capnproto.Text.Builder getHtmlInstructions() {
          return _getPointerField(org.capnproto.Text.factory, 5, null, 0, 0);
        }
        public final void setHtmlInstructions(org.capnproto.Text.Reader value) {
          _setPointerField(org.capnproto.Text.factory, 5, value);
        }
        public final void setHtmlInstructions(String value) {
          _setPointerField(org.capnproto.Text.factory, 5, new org.capnproto.Text.Reader(value));
        }
        public final org.capnproto.Text.Builder initHtmlInstructions(int size) {
          return _initPointerField(org.capnproto.Text.factory, 5, size);
        }
        public final boolean hasTravelMode() {
          return !_pointerFieldIsNull(6);
        }
        public final org.capnproto.Text.Builder getTravelMode() {
          return _getPointerField(org.capnproto.Text.factory, 6, null, 0, 0);
        }
        public final void setTravelMode(org.capnproto.Text.Reader value) {
          _setPointerField(org.capnproto.Text.factory, 6, value);
        }
        public final void setTravelMode(String value) {
          _setPointerField(org.capnproto.Text.factory, 6, new org.capnproto.Text.Reader(value));
        }
        public final org.capnproto.Text.Builder initTravelMode(int size) {
          return _initPointerField(org.capnproto.Text.factory, 6, size);
        }
      }

      public static final class Reader extends org.capnproto.StructReader {
        Reader(org.capnproto.SegmentReader segment, int data, int pointers,int dataSize, short pointerCount, int nestingLimit){
          super(segment, data, pointers, dataSize, pointerCount, nestingLimit);
        }

        public boolean hasDuration() {
          return !_pointerFieldIsNull(0);
        }
        public eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Distance.Reader getDuration() {
          return _getPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Distance.factory,0,null, 0);
        }

        public boolean hasEndLocation() {
          return !_pointerFieldIsNull(1);
        }
        public eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Northeast.Reader getEndLocation() {
          return _getPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Northeast.factory,1,null, 0);
        }

        public boolean hasDistance() {
          return !_pointerFieldIsNull(2);
        }
        public eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Distance.Reader getDistance() {
          return _getPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Distance.factory,2,null, 0);
        }

        public boolean hasStartLocation() {
          return !_pointerFieldIsNull(3);
        }
        public eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Northeast.Reader getStartLocation() {
          return _getPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Northeast.factory,3,null, 0);
        }

        public boolean hasPolyline() {
          return !_pointerFieldIsNull(4);
        }
        public eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.OverviewPolyline.Reader getPolyline() {
          return _getPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.OverviewPolyline.factory,4,null, 0);
        }

        public boolean hasHtmlInstructions() {
          return !_pointerFieldIsNull(5);
        }
        public org.capnproto.Text.Reader getHtmlInstructions() {
          return _getPointerField(org.capnproto.Text.factory, 5, null, 0, 0);
        }

        public boolean hasTravelMode() {
          return !_pointerFieldIsNull(6);
        }
        public org.capnproto.Text.Reader getTravelMode() {
          return _getPointerField(org.capnproto.Text.factory, 6, null, 0, 0);
        }

      }

    }


    public static class Legs {
      public static final org.capnproto.StructSize STRUCT_SIZE = new org.capnproto.StructSize((short)0,(short)9);
      public static final class Factory extends org.capnproto.StructFactory<Builder, Reader> {
        public Factory() {
        }
        public final Reader constructReader(org.capnproto.SegmentReader segment, int data,int pointers, int dataSize, short pointerCount, int nestingLimit) {
          return new Reader(segment,data,pointers,dataSize,pointerCount,nestingLimit);
        }
        public final Builder constructBuilder(org.capnproto.SegmentBuilder segment, int data,int pointers, int dataSize, short pointerCount) {
          return new Builder(segment, data, pointers, dataSize, pointerCount);
        }
        public final org.capnproto.StructSize structSize() {
          return Google.Legs.STRUCT_SIZE;
        }
        public final Reader asReader(Builder builder) {
          return builder.asReader();
        }
      }
      public static final Factory factory = new Factory();
      public static final org.capnproto.StructList.Factory<Builder,Reader> listFactory =
        new org.capnproto.StructList.Factory<Builder, Reader>(factory);
      public static final class Builder extends org.capnproto.StructBuilder {
        Builder(org.capnproto.SegmentBuilder segment, int data, int pointers,int dataSize, short pointerCount){
          super(segment, data, pointers, dataSize, pointerCount);
        }
        public final Reader asReader() {
          return new Reader(segment, data, pointers, dataSize, pointerCount, 0x7fffffff);
        }
        public final boolean hasTrafficSpeedEntry() {
          return !_pointerFieldIsNull(0);
        }
        public final org.capnproto.TextList.Builder getTrafficSpeedEntry() {
          return _getPointerField(org.capnproto.TextList.factory, 0, null, 0);
        }
        public final void setTrafficSpeedEntry(org.capnproto.TextList.Reader value) {
          _setPointerField(org.capnproto.TextList.factory, 0, value);
        }
        public final org.capnproto.TextList.Builder initTrafficSpeedEntry(int size) {
          return _initPointerField(org.capnproto.TextList.factory, 0, size);
        }
        public final eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Distance.Builder getDuration() {
          return _getPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Distance.factory, 1, null, 0);
        }
        public final void setDuration(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Distance.Reader value) {
          _setPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Distance.factory,1, value);
        }
        public final eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Distance.Builder initDuration() {
          return _initPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Distance.factory,1, 0);
        }
        public final boolean hasSteps() {
          return !_pointerFieldIsNull(2);
        }
        public final org.capnproto.StructList.Builder<eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Steps.Builder> getSteps() {
          return _getPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Steps.listFactory, 2, null, 0);
        }
        public final void setSteps(org.capnproto.StructList.Reader<eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Steps.Reader> value) {
          _setPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Steps.listFactory, 2, value);
        }
        public final org.capnproto.StructList.Builder<eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Steps.Builder> initSteps(int size) {
          return _initPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Steps.listFactory, 2, size);
        }
        public final boolean hasViaWaypoint() {
          return !_pointerFieldIsNull(3);
        }
        public final org.capnproto.TextList.Builder getViaWaypoint() {
          return _getPointerField(org.capnproto.TextList.factory, 3, null, 0);
        }
        public final void setViaWaypoint(org.capnproto.TextList.Reader value) {
          _setPointerField(org.capnproto.TextList.factory, 3, value);
        }
        public final org.capnproto.TextList.Builder initViaWaypoint(int size) {
          return _initPointerField(org.capnproto.TextList.factory, 3, size);
        }
        public final boolean hasStartAddress() {
          return !_pointerFieldIsNull(4);
        }
        public final org.capnproto.Text.Builder getStartAddress() {
          return _getPointerField(org.capnproto.Text.factory, 4, null, 0, 0);
        }
        public final void setStartAddress(org.capnproto.Text.Reader value) {
          _setPointerField(org.capnproto.Text.factory, 4, value);
        }
        public final void setStartAddress(String value) {
          _setPointerField(org.capnproto.Text.factory, 4, new org.capnproto.Text.Reader(value));
        }
        public final org.capnproto.Text.Builder initStartAddress(int size) {
          return _initPointerField(org.capnproto.Text.factory, 4, size);
        }
        public final boolean hasEndAddress() {
          return !_pointerFieldIsNull(5);
        }
        public final org.capnproto.Text.Builder getEndAddress() {
          return _getPointerField(org.capnproto.Text.factory, 5, null, 0, 0);
        }
        public final void setEndAddress(org.capnproto.Text.Reader value) {
          _setPointerField(org.capnproto.Text.factory, 5, value);
        }
        public final void setEndAddress(String value) {
          _setPointerField(org.capnproto.Text.factory, 5, new org.capnproto.Text.Reader(value));
        }
        public final org.capnproto.Text.Builder initEndAddress(int size) {
          return _initPointerField(org.capnproto.Text.factory, 5, size);
        }
        public final eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Northeast.Builder getEndLocation() {
          return _getPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Northeast.factory, 6, null, 0);
        }
        public final void setEndLocation(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Northeast.Reader value) {
          _setPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Northeast.factory,6, value);
        }
        public final eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Northeast.Builder initEndLocation() {
          return _initPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Northeast.factory,6, 0);
        }
        public final eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Distance.Builder getDistance() {
          return _getPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Distance.factory, 7, null, 0);
        }
        public final void setDistance(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Distance.Reader value) {
          _setPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Distance.factory,7, value);
        }
        public final eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Distance.Builder initDistance() {
          return _initPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Distance.factory,7, 0);
        }
        public final eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Northeast.Builder getStartLocation() {
          return _getPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Northeast.factory, 8, null, 0);
        }
        public final void setStartLocation(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Northeast.Reader value) {
          _setPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Northeast.factory,8, value);
        }
        public final eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Northeast.Builder initStartLocation() {
          return _initPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Northeast.factory,8, 0);
        }
      }

      public static final class Reader extends org.capnproto.StructReader {
        Reader(org.capnproto.SegmentReader segment, int data, int pointers,int dataSize, short pointerCount, int nestingLimit){
          super(segment, data, pointers, dataSize, pointerCount, nestingLimit);
        }

        public final boolean hasTrafficSpeedEntry() {
          return !_pointerFieldIsNull(0);
        }
        public final org.capnproto.TextList.Reader getTrafficSpeedEntry() {
          return _getPointerField(org.capnproto.TextList.factory, 0, null, 0);
        }

        public boolean hasDuration() {
          return !_pointerFieldIsNull(1);
        }
        public eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Distance.Reader getDuration() {
          return _getPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Distance.factory,1,null, 0);
        }

        public final boolean hasSteps() {
          return !_pointerFieldIsNull(2);
        }
        public final org.capnproto.StructList.Reader<eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Steps.Reader> getSteps() {
          return _getPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Steps.listFactory, 2, null, 0);
        }

        public final boolean hasViaWaypoint() {
          return !_pointerFieldIsNull(3);
        }
        public final org.capnproto.TextList.Reader getViaWaypoint() {
          return _getPointerField(org.capnproto.TextList.factory, 3, null, 0);
        }

        public boolean hasStartAddress() {
          return !_pointerFieldIsNull(4);
        }
        public org.capnproto.Text.Reader getStartAddress() {
          return _getPointerField(org.capnproto.Text.factory, 4, null, 0, 0);
        }

        public boolean hasEndAddress() {
          return !_pointerFieldIsNull(5);
        }
        public org.capnproto.Text.Reader getEndAddress() {
          return _getPointerField(org.capnproto.Text.factory, 5, null, 0, 0);
        }

        public boolean hasEndLocation() {
          return !_pointerFieldIsNull(6);
        }
        public eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Northeast.Reader getEndLocation() {
          return _getPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Northeast.factory,6,null, 0);
        }

        public boolean hasDistance() {
          return !_pointerFieldIsNull(7);
        }
        public eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Distance.Reader getDistance() {
          return _getPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Distance.factory,7,null, 0);
        }

        public boolean hasStartLocation() {
          return !_pointerFieldIsNull(8);
        }
        public eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Northeast.Reader getStartLocation() {
          return _getPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Northeast.factory,8,null, 0);
        }

      }

    }


    public static class Routes {
      public static final org.capnproto.StructSize STRUCT_SIZE = new org.capnproto.StructSize((short)0,(short)7);
      public static final class Factory extends org.capnproto.StructFactory<Builder, Reader> {
        public Factory() {
        }
        public final Reader constructReader(org.capnproto.SegmentReader segment, int data,int pointers, int dataSize, short pointerCount, int nestingLimit) {
          return new Reader(segment,data,pointers,dataSize,pointerCount,nestingLimit);
        }
        public final Builder constructBuilder(org.capnproto.SegmentBuilder segment, int data,int pointers, int dataSize, short pointerCount) {
          return new Builder(segment, data, pointers, dataSize, pointerCount);
        }
        public final org.capnproto.StructSize structSize() {
          return Google.Routes.STRUCT_SIZE;
        }
        public final Reader asReader(Builder builder) {
          return builder.asReader();
        }
      }
      public static final Factory factory = new Factory();
      public static final org.capnproto.StructList.Factory<Builder,Reader> listFactory =
        new org.capnproto.StructList.Factory<Builder, Reader>(factory);
      public static final class Builder extends org.capnproto.StructBuilder {
        Builder(org.capnproto.SegmentBuilder segment, int data, int pointers,int dataSize, short pointerCount){
          super(segment, data, pointers, dataSize, pointerCount);
        }
        public final Reader asReader() {
          return new Reader(segment, data, pointers, dataSize, pointerCount, 0x7fffffff);
        }
        public final eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Bounds.Builder getBounds() {
          return _getPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Bounds.factory, 0, null, 0);
        }
        public final void setBounds(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Bounds.Reader value) {
          _setPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Bounds.factory,0, value);
        }
        public final eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Bounds.Builder initBounds() {
          return _initPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Bounds.factory,0, 0);
        }
        public final boolean hasWarnings() {
          return !_pointerFieldIsNull(1);
        }
        public final org.capnproto.TextList.Builder getWarnings() {
          return _getPointerField(org.capnproto.TextList.factory, 1, null, 0);
        }
        public final void setWarnings(org.capnproto.TextList.Reader value) {
          _setPointerField(org.capnproto.TextList.factory, 1, value);
        }
        public final org.capnproto.TextList.Builder initWarnings(int size) {
          return _initPointerField(org.capnproto.TextList.factory, 1, size);
        }
        public final eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.OverviewPolyline.Builder getOverviewPolyline() {
          return _getPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.OverviewPolyline.factory, 2, null, 0);
        }
        public final void setOverviewPolyline(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.OverviewPolyline.Reader value) {
          _setPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.OverviewPolyline.factory,2, value);
        }
        public final eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.OverviewPolyline.Builder initOverviewPolyline() {
          return _initPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.OverviewPolyline.factory,2, 0);
        }
        public final boolean hasWaypointOrder() {
          return !_pointerFieldIsNull(3);
        }
        public final org.capnproto.TextList.Builder getWaypointOrder() {
          return _getPointerField(org.capnproto.TextList.factory, 3, null, 0);
        }
        public final void setWaypointOrder(org.capnproto.TextList.Reader value) {
          _setPointerField(org.capnproto.TextList.factory, 3, value);
        }
        public final org.capnproto.TextList.Builder initWaypointOrder(int size) {
          return _initPointerField(org.capnproto.TextList.factory, 3, size);
        }
        public final boolean hasLegs() {
          return !_pointerFieldIsNull(4);
        }
        public final org.capnproto.StructList.Builder<eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Legs.Builder> getLegs() {
          return _getPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Legs.listFactory, 4, null, 0);
        }
        public final void setLegs(org.capnproto.StructList.Reader<eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Legs.Reader> value) {
          _setPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Legs.listFactory, 4, value);
        }
        public final org.capnproto.StructList.Builder<eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Legs.Builder> initLegs(int size) {
          return _initPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Legs.listFactory, 4, size);
        }
        public final boolean hasSummary() {
          return !_pointerFieldIsNull(5);
        }
        public final org.capnproto.Text.Builder getSummary() {
          return _getPointerField(org.capnproto.Text.factory, 5, null, 0, 0);
        }
        public final void setSummary(org.capnproto.Text.Reader value) {
          _setPointerField(org.capnproto.Text.factory, 5, value);
        }
        public final void setSummary(String value) {
          _setPointerField(org.capnproto.Text.factory, 5, new org.capnproto.Text.Reader(value));
        }
        public final org.capnproto.Text.Builder initSummary(int size) {
          return _initPointerField(org.capnproto.Text.factory, 5, size);
        }
        public final boolean hasCopyrights() {
          return !_pointerFieldIsNull(6);
        }
        public final org.capnproto.Text.Builder getCopyrights() {
          return _getPointerField(org.capnproto.Text.factory, 6, null, 0, 0);
        }
        public final void setCopyrights(org.capnproto.Text.Reader value) {
          _setPointerField(org.capnproto.Text.factory, 6, value);
        }
        public final void setCopyrights(String value) {
          _setPointerField(org.capnproto.Text.factory, 6, new org.capnproto.Text.Reader(value));
        }
        public final org.capnproto.Text.Builder initCopyrights(int size) {
          return _initPointerField(org.capnproto.Text.factory, 6, size);
        }
      }

      public static final class Reader extends org.capnproto.StructReader {
        Reader(org.capnproto.SegmentReader segment, int data, int pointers,int dataSize, short pointerCount, int nestingLimit){
          super(segment, data, pointers, dataSize, pointerCount, nestingLimit);
        }

        public boolean hasBounds() {
          return !_pointerFieldIsNull(0);
        }
        public eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Bounds.Reader getBounds() {
          return _getPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Bounds.factory,0,null, 0);
        }

        public final boolean hasWarnings() {
          return !_pointerFieldIsNull(1);
        }
        public final org.capnproto.TextList.Reader getWarnings() {
          return _getPointerField(org.capnproto.TextList.factory, 1, null, 0);
        }

        public boolean hasOverviewPolyline() {
          return !_pointerFieldIsNull(2);
        }
        public eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.OverviewPolyline.Reader getOverviewPolyline() {
          return _getPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.OverviewPolyline.factory,2,null, 0);
        }

        public final boolean hasWaypointOrder() {
          return !_pointerFieldIsNull(3);
        }
        public final org.capnproto.TextList.Reader getWaypointOrder() {
          return _getPointerField(org.capnproto.TextList.factory, 3, null, 0);
        }

        public final boolean hasLegs() {
          return !_pointerFieldIsNull(4);
        }
        public final org.capnproto.StructList.Reader<eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Legs.Reader> getLegs() {
          return _getPointerField(eu.hippix.bsctest.data.capnp.GoogleCapnp.Google.Legs.listFactory, 4, null, 0);
        }

        public boolean hasSummary() {
          return !_pointerFieldIsNull(5);
        }
        public org.capnproto.Text.Reader getSummary() {
          return _getPointerField(org.capnproto.Text.factory, 5, null, 0, 0);
        }

        public boolean hasCopyrights() {
          return !_pointerFieldIsNull(6);
        }
        public org.capnproto.Text.Reader getCopyrights() {
          return _getPointerField(org.capnproto.Text.factory, 6, null, 0, 0);
        }

      }

    }


    public static class GeocodedWaypoints {
      public static final org.capnproto.StructSize STRUCT_SIZE = new org.capnproto.StructSize((short)0,(short)3);
      public static final class Factory extends org.capnproto.StructFactory<Builder, Reader> {
        public Factory() {
        }
        public final Reader constructReader(org.capnproto.SegmentReader segment, int data,int pointers, int dataSize, short pointerCount, int nestingLimit) {
          return new Reader(segment,data,pointers,dataSize,pointerCount,nestingLimit);
        }
        public final Builder constructBuilder(org.capnproto.SegmentBuilder segment, int data,int pointers, int dataSize, short pointerCount) {
          return new Builder(segment, data, pointers, dataSize, pointerCount);
        }
        public final org.capnproto.StructSize structSize() {
          return Google.GeocodedWaypoints.STRUCT_SIZE;
        }
        public final Reader asReader(Builder builder) {
          return builder.asReader();
        }
      }
      public static final Factory factory = new Factory();
      public static final org.capnproto.StructList.Factory<Builder,Reader> listFactory =
        new org.capnproto.StructList.Factory<Builder, Reader>(factory);
      public static final class Builder extends org.capnproto.StructBuilder {
        Builder(org.capnproto.SegmentBuilder segment, int data, int pointers,int dataSize, short pointerCount){
          super(segment, data, pointers, dataSize, pointerCount);
        }
        public final Reader asReader() {
          return new Reader(segment, data, pointers, dataSize, pointerCount, 0x7fffffff);
        }
        public final boolean hasPlaceId() {
          return !_pointerFieldIsNull(0);
        }
        public final org.capnproto.Text.Builder getPlaceId() {
          return _getPointerField(org.capnproto.Text.factory, 0, null, 0, 0);
        }
        public final void setPlaceId(org.capnproto.Text.Reader value) {
          _setPointerField(org.capnproto.Text.factory, 0, value);
        }
        public final void setPlaceId(String value) {
          _setPointerField(org.capnproto.Text.factory, 0, new org.capnproto.Text.Reader(value));
        }
        public final org.capnproto.Text.Builder initPlaceId(int size) {
          return _initPointerField(org.capnproto.Text.factory, 0, size);
        }
        public final boolean hasGeocoderStatus() {
          return !_pointerFieldIsNull(1);
        }
        public final org.capnproto.Text.Builder getGeocoderStatus() {
          return _getPointerField(org.capnproto.Text.factory, 1, null, 0, 0);
        }
        public final void setGeocoderStatus(org.capnproto.Text.Reader value) {
          _setPointerField(org.capnproto.Text.factory, 1, value);
        }
        public final void setGeocoderStatus(String value) {
          _setPointerField(org.capnproto.Text.factory, 1, new org.capnproto.Text.Reader(value));
        }
        public final org.capnproto.Text.Builder initGeocoderStatus(int size) {
          return _initPointerField(org.capnproto.Text.factory, 1, size);
        }
        public final boolean hasTypes() {
          return !_pointerFieldIsNull(2);
        }
        public final org.capnproto.TextList.Builder getTypes() {
          return _getPointerField(org.capnproto.TextList.factory, 2, null, 0);
        }
        public final void setTypes(org.capnproto.TextList.Reader value) {
          _setPointerField(org.capnproto.TextList.factory, 2, value);
        }
        public final org.capnproto.TextList.Builder initTypes(int size) {
          return _initPointerField(org.capnproto.TextList.factory, 2, size);
        }
      }

      public static final class Reader extends org.capnproto.StructReader {
        Reader(org.capnproto.SegmentReader segment, int data, int pointers,int dataSize, short pointerCount, int nestingLimit){
          super(segment, data, pointers, dataSize, pointerCount, nestingLimit);
        }

        public boolean hasPlaceId() {
          return !_pointerFieldIsNull(0);
        }
        public org.capnproto.Text.Reader getPlaceId() {
          return _getPointerField(org.capnproto.Text.factory, 0, null, 0, 0);
        }

        public boolean hasGeocoderStatus() {
          return !_pointerFieldIsNull(1);
        }
        public org.capnproto.Text.Reader getGeocoderStatus() {
          return _getPointerField(org.capnproto.Text.factory, 1, null, 0, 0);
        }

        public final boolean hasTypes() {
          return !_pointerFieldIsNull(2);
        }
        public final org.capnproto.TextList.Reader getTypes() {
          return _getPointerField(org.capnproto.TextList.factory, 2, null, 0);
        }

      }

    }


  }



public static final class Schemas {
public static final org.capnproto.SegmentReader b_bf24746b7b27f7c6 = loadSchema();

private static org.capnproto.SegmentReader loadSchema() {
  try (java.io.InputStream is = BestbuyCapnp.class.getResourceAsStream("/eu/hippix/bsctest/data/capnp/bestbuy.capnp.bin")) {
    byte[] bytes = is.readAllBytes();
    java.nio.ByteBuffer buf = java.nio.ByteBuffer.wrap(bytes);
    return new org.capnproto.SegmentReader(buf, null);
  } catch (java.io.IOException e) {
    throw new RuntimeException("Failed to load schema", e);
  }
}}}
